name: Node auto-update

on:
  schedule:
    # First day of the month.
    - cron: "0 6 1 * *"
  workflow_dispatch:

jobs:
  update-node:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Update schema
        id: node-version
        run: |
          latest=$(curl -s https://nodejs.org/dist/index.json | jq -r 'map(select(.lts))[0].version' | sed 's/v//')
          major=$(echo "$latest" | cut -d. -f1)

          echo "latest=$latest" >> $GITHUB_OUTPUT
          echo "major=$major" >> $GITHUB_OUTPUT

      - name: Update .node-version
        env:
          LATEST: ${{ steps.node-version.outputs.latest }}
        run: echo "v${LATEST}" > .node-version

      - name: Update @types/node package
        if: hashFiles('tsconfig.json') != ''
        env:
          MAJOR: ${{ steps.node-version.outputs.major }}
        # zizmor: ignore[adhoc-packages] This is intentional
        run: npm install --save-dev @types/node@${MAJOR}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          add-paths: |
            .node-version
            package.json
            package-lock.json
          commit-message: "[Auto] Update Node version"
          branch: auto-update/node
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "[Auto] Update script Node version"
          body: |
            Automatic update for the version of Node being used.
